#! /bin/sh
### BEGIN INIT INFO
# Provides:          omf-rc
# Required-Start:    $ALL
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

PATH=$PATH:/usr/local/bin
DAEMON=/usr/local/bin/run_omf_rc.sh
[ -x "$DAEMON" ] || exit 0
NAME=omf_rc
PIDFILE=/var/run/$NAME.pid
. /etc/rc.d/init.d/functions

start(){
    echo -n "Starting OMF Resource Controller: $NAME"
    $DAEMON 2>&1 | logger -t omf_rc &
    echo $! > $PIDFILE
    echo "."
}

stop(){
    echo -n "Stopping OMF Resource Controller: $NAME"
    if [ -f $PIDFILE ]; then
	kill `cat $PIDFILE`
	rm $PIDFILE
	sleep 2
    else
	echo -e "\nNo pidfile found. Is $NAME running?"
    fi
    echo "."
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|force-reload)
 	stop
 	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart|force-reload}" >&2
	exit 3
	;;
esac

:
