#! /bin/sh
#
# gridService init script to start gridService daemon
#
#     Written by Maximilian Ott <max@winlab.rutgers.edu>.
#     Modified by Christoph Dwertmann
#
# Version: $Id:$
#

NAME=gridservices2

test -x /usr/sbin/$NAME || exit 0

if [ -f /etc/gridservices2/gridservices.cfg ]; then
   . /etc/gridservices2/gridservices.cfg
fi

if [ -f /etc/default/$NAME ]; then
    . /etc/default/$NAME
fi

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"


start(){
        echo -n "Starting Orbit Gridservice: $NAME"
	PORT=`echo $OPTS | sed 's/[^0-9]*//g'`
	while [ `netstat -ltn | grep $PORT -c` -ne 0 ] ; do
	   echo -n "\nWaiting for release of port $PORT..."
	   sleep 3
	done
	start-stop-daemon --start --background --pidfile /var/run/$NAME.pid --make-pidfile --exec /usr/sbin/$NAME -- $OPTS
        echo "..done."
}

stop(){
        echo -n "Stopping Orbit Gridservice: $NAME"
	start-stop-daemon --stop --signal 2 --oknodo --pidfile /var/run/$NAME.pid
        echo "..done."
}


case "$1" in
  start)
        start
	;;
  stop)
        stop
	;;

  restart)
	stop
	start
	;;

  *)
	echo "Usage: /etc/init.d/$NAME {start|stop|restart}"
	exit 1
esac

exit 0

