#$:.unshift(File.dirname(__FILE__) + '/../omf-common/ruby')
#$:.unshift(File.dirname(__FILE__) + '/../ruby')

require 'rake'
require 'rake/clean'
require 'rake/testtask'
require 'rake/rdoctask'
require 'fileutils'
include FileUtils


$VERBOSE = nil

desc "Run all the unit tests"
task :default => [:test]

#setup_tests

desc "Run the unit tests in test"
Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.test_files = FileList['test/*_test.rb']
  t.verbose = true
end


# Generate the RDoc documentation
Rake::RDocTask.new(:doc) { |rdoc|
  rdoc.main = 'README'
  rdoc.rdoc_files.include('ruby/**/*.rb')
#  rdoc.rdoc_files.include('README', 'GPL', 'COPYING')
  rdoc.rdoc_dir = 'docs'
  rdoc.title    = "OMF Commons"
  rdoc.options.concat ['--line-numbers', '--inline-source']
}
