source "http://rubygems.org"

# Specify your gem's dependencies in omf_ec.gemspec
gemspec

gem 'omf_common', path: "../omf_common"

group :test do
  gem 'rake'
end

group :xmpp do
  gem 'blather'
end
