#! /bin/sh
#
# nodeagent init script to start nodeagent daemon
#
#     Written by Maximilian Ott <max@winlab.rutgers.edu>.
#     Modified by Christoph Dwertmann
#
# Version: $Id:$
#

NAME=nodeagent4

test -x /usr/sbin/$NAME || exit 0

if [ -f /etc/$NAME/nodeagent.cfg ]; then
   . /etc/$NAME/nodeagent.cfg
fi

if [ -f /etc/default/$NAME ]; then
    . /etc/default/$NAME
fi

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

start(){
        echo -n "Starting Orbit Nodeagent: $NAME"
	if [ -f /var/log/nodeAgent4.log ]; then
	    mv /var/log/nodeAgent4.log /var/log/nodeAgent4.log.1
	fi
	start-stop-daemon --start --quiet --background --pidfile /var/run/$NAME.pid --make-pidfile --exec /usr/sbin/$NAME -- $OPTS
        echo "."
}

stop(){
        echo -n "Stopping Orbit Nodeagent: $NAME"
	start-stop-daemon --stop --quiet --oknodo --pidfile /var/run/$NAME.pid
        echo "."
}

case "$1" in
  start)
        start
	;;
  stop)
        stop
	;;

  restart)
        stop
	start
	;;

  *)
	echo "Usage: /etc/init.d/$NAME {start|stop|restart}"
	exit 1
esac

exit 0

