require 'rake/testtask'
require "bundler/gem_tasks"

task :default => :test

Rake::TestTask.new do |t|
  t.libs << 'test'
  t.pattern = "test/**/*_spec.rb"
  t.verbose = true
end

Rake::TestTask.new(:integration) do |t|
  t.libs << 'integration_test'
  t.pattern = "integration_test/**/*_spec.rb"
  t.verbose = true
end
