.\" Manpage for omf-expctl-5.4.
.TH man 1 "05 July 2010" "5.4" "omf-expctl-5.4 man page"
.SH NAME
omf-expctl-5.4 \- run OMF experiments
.SH SYNOPSIS
omf-expctl-5.4 [OPTION]
.SH DESCRIPTION
omf-expctl-5.4 is ...
.SH OPTIONS
The omf-expctl-5.4 has ...
.SH SEE ALSO
useradd(8)
.SH BUGS
No known bugs.
.SH AUTHOR
Christoph Dwertmann (christoph.dwertmann@nicta.com.au)
