#!/bin/sh
CMD="internal1.orbit-lab.org/register.html?name=node$2-$3&"
for  i in eth0 eth1 eth2 eth3 eth4 ath0 ath1
do
        echo -n "$i: "
	MAC=`/usr/sbin/getmac $i 2> /dev/null`
		if [ $? -eq 0 ] ; then
			echo $MAC
			CMD="$CMD&$i=$MAC"
		else
			echo "No device"
		fi
done
/usr/bin/wget http://$CMD
